# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainclone', '0009_auto_20180729_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saves',
            options={'ordering': ['-pk']},
        ),
    ]
